### PR TITLE
Optimised addMany method of JsonDatabase

### LINKED ISSUE #40: Make addMany method more effieicent
Hactoberfest - task

Issue - 

Currently the JsonStorage.addMany updates the file on every iteration of the for loop. Thus hindering performance when a large amount data is passed on to the method.

Fix - 
Move the dump function out of the for loop.

### PR DESCRIPTION
**Pull request by ajratnam**
### What did I change?
I improved the addMany method of the JsonDatabse object.

### Why did I change it?
It had some redundant code.
It also fixes #40

### CODE REVIEW

**Comment by ajratnam** [comment]
Please let me know if I have to change anything or is this ok?

**Review by Adwaith-Rajesh — APPROVED** [review]
LGTM

**Review by fredysomy — CHANGES_REQUESTED** [review]
Hey @ajratnam code LGTM

Can you also add changlelog to v1.6.0 (considering the change as a enhancement)

And also bump the version in setup.py



LGTM.

Thanks for the contribution.🤩🤩

**Comment by ajratnam** [comment]
Thanks, appreciate it!! I will update the changelog.

**Comment by ajratnam** [comment]
@fredysomy I should put all the changes from dev to 1.6.0 right?

**Comment by ajratnam** [comment]
Sorry I understood now, I shall update my change to 1.6.0.

**Comment by ajratnam** [comment]
Yes I updated it, is it fine?

**Comment by fredysomy** [comment]
Oh yes @ajratnam . This LGTM

Thankyou for your contribution.🤩

**Review by fredysomy — APPROVED** [review]

**Pull request merged**
